// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-TGz7jkB1vEKj7TiEkmvnI2ON-08oA8',
    appId: '1:690263266063:android:7b803cdf0aa25716aca47a',
    messagingSenderId: '690263266063',
    projectId: 'screen-sage-dfef4',
    storageBucket: 'screen-sage-dfef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjZTLR2fDdZW5x0y3sibD3G8dvqDKgqc',
    appId: '1:690263266063:ios:0e1533c66c0cae05aca47a',
    messagingSenderId: '690263266063',
    projectId: 'screen-sage-dfef4',
    storageBucket: 'screen-sage-dfef4.firebasestorage.app',
    androidClientId: '690263266063-r1987igq1dtd9n9q5iqc486qihv2hkir.apps.googleusercontent.com',
    iosClientId: '690263266063-hbrfqp533vq4otojhm9fh9bjl0cbcpoq.apps.googleusercontent.com',
    iosBundleId: 'com.pratham.screensage',
  );

}